// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: komitake/admin/v1/admin.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State mirrors the daemon lifecycle. STATE_UNSPECIFIED is never sent by the
// daemon; it exists so an unset field is distinguishable from DOWN.
type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_STATE_DOWN        State = 1
	State_STATE_RUNNING     State = 2
	State_STATE_PAIRING     State = 3
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_DOWN",
		2: "STATE_RUNNING",
		3: "STATE_PAIRING",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_DOWN":        1,
		"STATE_RUNNING":     2,
		"STATE_PAIRING":     3,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_komitake_admin_v1_admin_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_komitake_admin_v1_admin_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

// PairingRecord is the pairing-session metadata persisted to pairing.json and
// surfaced over the API. The seed is equivalent to the network key, so callers
// must treat it as a secret.
type PairingRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         State                  `protobuf:"varint,1,opt,name=state,proto3,enum=komitake.admin.v1.State" json:"state,omitempty"`
	SeedHex       string                 `protobuf:"bytes,2,opt,name=seed_hex,json=seedHex,proto3" json:"seed_hex,omitempty"`
	Ssid          string                 `protobuf:"bytes,3,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Channel       uint32                 `protobuf:"varint,4,opt,name=channel,proto3" json:"channel,omitempty"`
	GeneratedAt   string                 `protobuf:"bytes,5,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	FilePath      string                 `protobuf:"bytes,6,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingRecord) Reset() {
	*x = PairingRecord{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingRecord) ProtoMessage() {}

func (x *PairingRecord) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingRecord.ProtoReflect.Descriptor instead.
func (*PairingRecord) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *PairingRecord) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *PairingRecord) GetSeedHex() string {
	if x != nil {
		return x.SeedHex
	}
	return ""
}

func (x *PairingRecord) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *PairingRecord) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *PairingRecord) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

func (x *PairingRecord) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

// WirelessInfo is non-secret AP/runtime networking, safe for diagnostics.
type WirelessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Subnet        string                 `protobuf:"bytes,3,opt,name=subnet,proto3" json:"subnet,omitempty"`
	Channel       uint32                 `protobuf:"varint,4,opt,name=channel,proto3" json:"channel,omitempty"`
	Ssid          string                 `protobuf:"bytes,5,opt,name=ssid,proto3" json:"ssid,omitempty"`
	HostapdPath   string                 `protobuf:"bytes,6,opt,name=hostapd_path,json=hostapdPath,proto3" json:"hostapd_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WirelessInfo) Reset() {
	*x = WirelessInfo{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WirelessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WirelessInfo) ProtoMessage() {}

func (x *WirelessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WirelessInfo.ProtoReflect.Descriptor instead.
func (*WirelessInfo) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *WirelessInfo) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *WirelessInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WirelessInfo) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *WirelessInfo) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *WirelessInfo) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *WirelessInfo) GetHostapdPath() string {
	if x != nil {
		return x.HostapdPath
	}
	return ""
}

// DeviceSummary describes a kart whose handshake is currently held open.
// Serial is the serial number reported by the device (Fuji product_code)
// when the control port has answered; it may be empty briefly after connect.
type DeviceSummary struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Kind       string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Ident      string                 `protobuf:"bytes,2,opt,name=ident,proto3" json:"ident,omitempty"`
	Address    string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	MacAddress string                 `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	SignalDbm  *int32                 `protobuf:"varint,5,opt,name=signal_dbm,json=signalDbm,proto3,oneof" json:"signal_dbm,omitempty"`
	Serial     string                 `protobuf:"bytes,6,opt,name=serial,proto3" json:"serial,omitempty"`
	// Battery is the documented HUD bar count from telemetry type 0x01 (0-4).
	Battery *int32 `protobuf:"varint,7,opt,name=battery,proto3,oneof" json:"battery,omitempty"`
	// CableConnected is status byte 0 bit 0x01 from telemetry type 0x01.
	CableConnected *bool `protobuf:"varint,8,opt,name=cable_connected,json=cableConnected,proto3,oneof" json:"cable_connected,omitempty"`
	// DriveArmed is local daemon control-session state.
	DriveArmed    bool    `protobuf:"varint,9,opt,name=drive_armed,json=driveArmed,proto3" json:"drive_armed,omitempty"`
	AccelMps2     *Vec3   `protobuf:"bytes,10,opt,name=accel_mps2,json=accelMps2,proto3" json:"accel_mps2,omitempty"`
	GyroDps       *Vec3   `protobuf:"bytes,11,opt,name=gyro_dps,json=gyroDps,proto3" json:"gyro_dps,omitempty"`
	Orientation   *Quat   `protobuf:"bytes,12,opt,name=orientation,proto3" json:"orientation,omitempty"`
	ImuTimerUs    *uint32 `protobuf:"varint,13,opt,name=imu_timer_us,json=imuTimerUs,proto3,oneof" json:"imu_timer_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceSummary) Reset() {
	*x = DeviceSummary{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSummary) ProtoMessage() {}

func (x *DeviceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSummary.ProtoReflect.Descriptor instead.
func (*DeviceSummary) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceSummary) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DeviceSummary) GetIdent() string {
	if x != nil {
		return x.Ident
	}
	return ""
}

func (x *DeviceSummary) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DeviceSummary) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *DeviceSummary) GetSignalDbm() int32 {
	if x != nil && x.SignalDbm != nil {
		return *x.SignalDbm
	}
	return 0
}

func (x *DeviceSummary) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DeviceSummary) GetBattery() int32 {
	if x != nil && x.Battery != nil {
		return *x.Battery
	}
	return 0
}

func (x *DeviceSummary) GetCableConnected() bool {
	if x != nil && x.CableConnected != nil {
		return *x.CableConnected
	}
	return false
}

func (x *DeviceSummary) GetDriveArmed() bool {
	if x != nil {
		return x.DriveArmed
	}
	return false
}

func (x *DeviceSummary) GetAccelMps2() *Vec3 {
	if x != nil {
		return x.AccelMps2
	}
	return nil
}

func (x *DeviceSummary) GetGyroDps() *Vec3 {
	if x != nil {
		return x.GyroDps
	}
	return nil
}

func (x *DeviceSummary) GetOrientation() *Quat {
	if x != nil {
		return x.Orientation
	}
	return nil
}

func (x *DeviceSummary) GetImuTimerUs() uint32 {
	if x != nil && x.ImuTimerUs != nil {
		return *x.ImuTimerUs
	}
	return 0
}

type Vec3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec3) Reset() {
	*x = Vec3{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec3) ProtoMessage() {}

func (x *Vec3) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec3.ProtoReflect.Descriptor instead.
func (*Vec3) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *Vec3) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec3) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vec3) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Quat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	I             float64                `protobuf:"fixed64,1,opt,name=i,proto3" json:"i,omitempty"`
	J             float64                `protobuf:"fixed64,2,opt,name=j,proto3" json:"j,omitempty"`
	K             float64                `protobuf:"fixed64,3,opt,name=k,proto3" json:"k,omitempty"`
	R             float64                `protobuf:"fixed64,4,opt,name=r,proto3" json:"r,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quat) Reset() {
	*x = Quat{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quat) ProtoMessage() {}

func (x *Quat) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quat.ProtoReflect.Descriptor instead.
func (*Quat) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *Quat) GetI() float64 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *Quat) GetJ() float64 {
	if x != nil {
		return x.J
	}
	return 0
}

func (x *Quat) GetK() float64 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *Quat) GetR() float64 {
	if x != nil {
		return x.R
	}
	return 0
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         State                  `protobuf:"varint,1,opt,name=state,proto3,enum=komitake.admin.v1.State" json:"state,omitempty"`
	Pairing       *PairingRecord         `protobuf:"bytes,2,opt,name=pairing,proto3" json:"pairing,omitempty"`
	Wireless      *WirelessInfo          `protobuf:"bytes,3,opt,name=wireless,proto3" json:"wireless,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *GetStateResponse) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *GetStateResponse) GetPairing() *PairingRecord {
	if x != nil {
		return x.Pairing
	}
	return nil
}

func (x *GetStateResponse) GetWireless() *WirelessInfo {
	if x != nil {
		return x.Wireless
	}
	return nil
}

type SetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         State                  `protobuf:"varint,1,opt,name=state,proto3,enum=komitake.admin.v1.State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStateRequest) Reset() {
	*x = SetStateRequest{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateRequest) ProtoMessage() {}

func (x *SetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateRequest.ProtoReflect.Descriptor instead.
func (*SetStateRequest) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *SetStateRequest) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

type SetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         State                  `protobuf:"varint,1,opt,name=state,proto3,enum=komitake.admin.v1.State" json:"state,omitempty"`
	Pairing       *PairingRecord         `protobuf:"bytes,2,opt,name=pairing,proto3" json:"pairing,omitempty"`
	Wireless      *WirelessInfo          `protobuf:"bytes,3,opt,name=wireless,proto3" json:"wireless,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStateResponse) Reset() {
	*x = SetStateResponse{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateResponse) ProtoMessage() {}

func (x *SetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateResponse.ProtoReflect.Descriptor instead.
func (*SetStateResponse) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *SetStateResponse) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *SetStateResponse) GetPairing() *PairingRecord {
	if x != nil {
		return x.Pairing
	}
	return nil
}

func (x *SetStateResponse) GetWireless() *WirelessInfo {
	if x != nil {
		return x.Wireless
	}
	return nil
}

type GetPairingInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPairingInfoRequest) Reset() {
	*x = GetPairingInfoRequest{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPairingInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPairingInfoRequest) ProtoMessage() {}

func (x *GetPairingInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPairingInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPairingInfoRequest) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

type GetPairingInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairing       *PairingRecord         `protobuf:"bytes,1,opt,name=pairing,proto3" json:"pairing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPairingInfoResponse) Reset() {
	*x = GetPairingInfoResponse{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPairingInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPairingInfoResponse) ProtoMessage() {}

func (x *GetPairingInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPairingInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPairingInfoResponse) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *GetPairingInfoResponse) GetPairing() *PairingRecord {
	if x != nil {
		return x.Pairing
	}
	return nil
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceSummary       `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *ListDevicesResponse) GetDevices() []*DeviceSummary {
	if x != nil {
		return x.Devices
	}
	return nil
}

type WaitForDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ident         string                 `protobuf:"bytes,1,opt,name=ident,proto3" json:"ident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForDeviceRequest) Reset() {
	*x = WaitForDeviceRequest{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForDeviceRequest) ProtoMessage() {}

func (x *WaitForDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForDeviceRequest.ProtoReflect.Descriptor instead.
func (*WaitForDeviceRequest) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *WaitForDeviceRequest) GetIdent() string {
	if x != nil {
		return x.Ident
	}
	return ""
}

type WaitForDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *DeviceSummary         `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForDeviceResponse) Reset() {
	*x = WaitForDeviceResponse{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForDeviceResponse) ProtoMessage() {}

func (x *WaitForDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForDeviceResponse.ProtoReflect.Descriptor instead.
func (*WaitForDeviceResponse) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *WaitForDeviceResponse) GetDevice() *DeviceSummary {
	if x != nil {
		return x.Device
	}
	return nil
}

// GetDeviceParamRequest selects a connected kart (ident or serial / unique
// prefix, same rules as CLI device selectors) and a Fuji param name.
type GetDeviceParamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceParamRequest) Reset() {
	*x = GetDeviceParamRequest{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceParamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceParamRequest) ProtoMessage() {}

func (x *GetDeviceParamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceParamRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceParamRequest) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *GetDeviceParamRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *GetDeviceParamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDeviceParamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *DeviceSummary         `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceParamResponse) Reset() {
	*x = GetDeviceParamResponse{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceParamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceParamResponse) ProtoMessage() {}

func (x *GetDeviceParamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceParamResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceParamResponse) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *GetDeviceParamResponse) GetDevice() *DeviceSummary {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *GetDeviceParamResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetProductCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductCodeRequest) Reset() {
	*x = GetProductCodeRequest{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductCodeRequest) ProtoMessage() {}

func (x *GetProductCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductCodeRequest.ProtoReflect.Descriptor instead.
func (*GetProductCodeRequest) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *GetProductCodeRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

// ProductCode is the decoded Fuji product_code parameter.
type ProductCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unk1          uint32                 `protobuf:"varint,1,opt,name=unk1,proto3" json:"unk1,omitempty"`
	Character     uint32                 `protobuf:"varint,2,opt,name=character,proto3" json:"character,omitempty"`
	Unk2          uint32                 `protobuf:"varint,3,opt,name=unk2,proto3" json:"unk2,omitempty"`
	Serial        string                 `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCode) Reset() {
	*x = ProductCode{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCode) ProtoMessage() {}

func (x *ProductCode) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCode.ProtoReflect.Descriptor instead.
func (*ProductCode) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *ProductCode) GetUnk1() uint32 {
	if x != nil {
		return x.Unk1
	}
	return 0
}

func (x *ProductCode) GetCharacter() uint32 {
	if x != nil {
		return x.Character
	}
	return 0
}

func (x *ProductCode) GetUnk2() uint32 {
	if x != nil {
		return x.Unk2
	}
	return 0
}

func (x *ProductCode) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type GetProductCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *DeviceSummary         `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	ProductCode   *ProductCode           `protobuf:"bytes,2,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductCodeResponse) Reset() {
	*x = GetProductCodeResponse{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductCodeResponse) ProtoMessage() {}

func (x *GetProductCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductCodeResponse.ProtoReflect.Descriptor instead.
func (*GetProductCodeResponse) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *GetProductCodeResponse) GetDevice() *DeviceSummary {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *GetProductCodeResponse) GetProductCode() *ProductCode {
	if x != nil {
		return x.ProductCode
	}
	return nil
}

type SetDriveRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Selector string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Steer    float64                `protobuf:"fixed64,2,opt,name=steer,proto3" json:"steer,omitempty"`
	Throttle float64                `protobuf:"fixed64,3,opt,name=throttle,proto3" json:"throttle,omitempty"`
	// Brake controls the physical kart brake-light byte independently of throttle.
	Brake         float64 `protobuf:"fixed64,4,opt,name=brake,proto3" json:"brake,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveRequest) Reset() {
	*x = SetDriveRequest{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveRequest) ProtoMessage() {}

func (x *SetDriveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveRequest.ProtoReflect.Descriptor instead.
func (*SetDriveRequest) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *SetDriveRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *SetDriveRequest) GetSteer() float64 {
	if x != nil {
		return x.Steer
	}
	return 0
}

func (x *SetDriveRequest) GetThrottle() float64 {
	if x != nil {
		return x.Throttle
	}
	return 0
}

func (x *SetDriveRequest) GetBrake() float64 {
	if x != nil {
		return x.Brake
	}
	return 0
}

type DriveState struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DeviceId string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Steer    float64                `protobuf:"fixed64,2,opt,name=steer,proto3" json:"steer,omitempty"`
	Throttle float64                `protobuf:"fixed64,3,opt,name=throttle,proto3" json:"throttle,omitempty"`
	// Brake is the requested physical brake-light state.
	Brake         float64 `protobuf:"fixed64,4,opt,name=brake,proto3" json:"brake,omitempty"`
	Applied       bool    `protobuf:"varint,5,opt,name=applied,proto3" json:"applied,omitempty"`
	UpdatedAt     string  `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Reason        string  `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriveState) Reset() {
	*x = DriveState{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriveState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriveState) ProtoMessage() {}

func (x *DriveState) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriveState.ProtoReflect.Descriptor instead.
func (*DriveState) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{21}
}

func (x *DriveState) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DriveState) GetSteer() float64 {
	if x != nil {
		return x.Steer
	}
	return 0
}

func (x *DriveState) GetThrottle() float64 {
	if x != nil {
		return x.Throttle
	}
	return 0
}

func (x *DriveState) GetBrake() float64 {
	if x != nil {
		return x.Brake
	}
	return 0
}

func (x *DriveState) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *DriveState) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *DriveState) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SetDriveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drive         *DriveState            `protobuf:"bytes,1,opt,name=drive,proto3" json:"drive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveResponse) Reset() {
	*x = SetDriveResponse{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveResponse) ProtoMessage() {}

func (x *SetDriveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveResponse.ProtoReflect.Descriptor instead.
func (*SetDriveResponse) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *SetDriveResponse) GetDrive() *DriveState {
	if x != nil {
		return x.Drive
	}
	return nil
}

type GetDriveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriveRequest) Reset() {
	*x = GetDriveRequest{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriveRequest) ProtoMessage() {}

func (x *GetDriveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriveRequest.ProtoReflect.Descriptor instead.
func (*GetDriveRequest) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{23}
}

func (x *GetDriveRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type GetDriveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drive         *DriveState            `protobuf:"bytes,1,opt,name=drive,proto3" json:"drive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriveResponse) Reset() {
	*x = GetDriveResponse{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriveResponse) ProtoMessage() {}

func (x *GetDriveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriveResponse.ProtoReflect.Descriptor instead.
func (*GetDriveResponse) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{24}
}

func (x *GetDriveResponse) GetDrive() *DriveState {
	if x != nil {
		return x.Drive
	}
	return nil
}

type SetDriveModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveModeRequest) Reset() {
	*x = SetDriveModeRequest{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveModeRequest) ProtoMessage() {}

func (x *SetDriveModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveModeRequest.ProtoReflect.Descriptor instead.
func (*SetDriveModeRequest) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{25}
}

func (x *SetDriveModeRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *SetDriveModeRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetDriveModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *DeviceSummary         `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveModeResponse) Reset() {
	*x = SetDriveModeResponse{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveModeResponse) ProtoMessage() {}

func (x *SetDriveModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveModeResponse.ProtoReflect.Descriptor instead.
func (*SetDriveModeResponse) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{26}
}

func (x *SetDriveModeResponse) GetDevice() *DeviceSummary {
	if x != nil {
		return x.Device
	}
	return nil
}

type ShutdownKartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownKartRequest) Reset() {
	*x = ShutdownKartRequest{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownKartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownKartRequest) ProtoMessage() {}

func (x *ShutdownKartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownKartRequest.ProtoReflect.Descriptor instead.
func (*ShutdownKartRequest) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{27}
}

func (x *ShutdownKartRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type ShutdownKartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *DeviceSummary         `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownKartResponse) Reset() {
	*x = ShutdownKartResponse{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownKartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownKartResponse) ProtoMessage() {}

func (x *ShutdownKartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownKartResponse.ProtoReflect.Descriptor instead.
func (*ShutdownKartResponse) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{28}
}

func (x *ShutdownKartResponse) GetDevice() *DeviceSummary {
	if x != nil {
		return x.Device
	}
	return nil
}

type StreamVideoRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Selector string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// FreshKeyFrame skips the cached GOP and starts at the next live IDR.
	FreshKeyFrame bool `protobuf:"varint,2,opt,name=fresh_key_frame,json=freshKeyFrame,proto3" json:"fresh_key_frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamVideoRequest) Reset() {
	*x = StreamVideoRequest{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamVideoRequest) ProtoMessage() {}

func (x *StreamVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamVideoRequest.ProtoReflect.Descriptor instead.
func (*StreamVideoRequest) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{29}
}

func (x *StreamVideoRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *StreamVideoRequest) GetFreshKeyFrame() bool {
	if x != nil {
		return x.FreshKeyFrame
	}
	return false
}

type StreamVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Metadata_0    uint64                 `protobuf:"varint,3,opt,name=metadata_0,json=metadata0,proto3" json:"metadata_0,omitempty"`
	Metadata_1    uint64                 `protobuf:"varint,4,opt,name=metadata_1,json=metadata1,proto3" json:"metadata_1,omitempty"`
	Metadata_2    uint64                 `protobuf:"varint,5,opt,name=metadata_2,json=metadata2,proto3" json:"metadata_2,omitempty"`
	KeyFrame      bool                   `protobuf:"varint,6,opt,name=key_frame,json=keyFrame,proto3" json:"key_frame,omitempty"`
	AnnexB        []byte                 `protobuf:"bytes,7,opt,name=annex_b,json=annexB,proto3" json:"annex_b,omitempty"`
	Discontinuity bool                   `protobuf:"varint,8,opt,name=discontinuity,proto3" json:"discontinuity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamVideoResponse) Reset() {
	*x = StreamVideoResponse{}
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamVideoResponse) ProtoMessage() {}

func (x *StreamVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_komitake_admin_v1_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamVideoResponse.ProtoReflect.Descriptor instead.
func (*StreamVideoResponse) Descriptor() ([]byte, []int) {
	return file_komitake_admin_v1_admin_proto_rawDescGZIP(), []int{30}
}

func (x *StreamVideoResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *StreamVideoResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *StreamVideoResponse) GetMetadata_0() uint64 {
	if x != nil {
		return x.Metadata_0
	}
	return 0
}

func (x *StreamVideoResponse) GetMetadata_1() uint64 {
	if x != nil {
		return x.Metadata_1
	}
	return 0
}

func (x *StreamVideoResponse) GetMetadata_2() uint64 {
	if x != nil {
		return x.Metadata_2
	}
	return 0
}

func (x *StreamVideoResponse) GetKeyFrame() bool {
	if x != nil {
		return x.KeyFrame
	}
	return false
}

func (x *StreamVideoResponse) GetAnnexB() []byte {
	if x != nil {
		return x.AnnexB
	}
	return nil
}

func (x *StreamVideoResponse) GetDiscontinuity() bool {
	if x != nil {
		return x.Discontinuity
	}
	return false
}

var File_komitake_admin_v1_admin_proto protoreflect.FileDescriptor

const file_komitake_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1dkomitake/admin/v1/admin.proto\x12\x11komitake.admin.v1\"\xc8\x01\n" +
	"\rPairingRecord\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.komitake.admin.v1.StateR\x05state\x12\x19\n" +
	"\bseed_hex\x18\x02 \x01(\tR\aseedHex\x12\x12\n" +
	"\x04ssid\x18\x03 \x01(\tR\x04ssid\x12\x18\n" +
	"\achannel\x18\x04 \x01(\rR\achannel\x12!\n" +
	"\fgenerated_at\x18\x05 \x01(\tR\vgeneratedAt\x12\x1b\n" +
	"\tfile_path\x18\x06 \x01(\tR\bfilePath\"\xaf\x01\n" +
	"\fWirelessInfo\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06subnet\x18\x03 \x01(\tR\x06subnet\x12\x18\n" +
	"\achannel\x18\x04 \x01(\rR\achannel\x12\x12\n" +
	"\x04ssid\x18\x05 \x01(\tR\x04ssid\x12!\n" +
	"\fhostapd_path\x18\x06 \x01(\tR\vhostapdPath\"\xac\x04\n" +
	"\rDeviceSummary\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05ident\x18\x02 \x01(\tR\x05ident\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1f\n" +
	"\vmac_address\x18\x04 \x01(\tR\n" +
	"macAddress\x12\"\n" +
	"\n" +
	"signal_dbm\x18\x05 \x01(\x05H\x00R\tsignalDbm\x88\x01\x01\x12\x16\n" +
	"\x06serial\x18\x06 \x01(\tR\x06serial\x12\x1d\n" +
	"\abattery\x18\a \x01(\x05H\x01R\abattery\x88\x01\x01\x12,\n" +
	"\x0fcable_connected\x18\b \x01(\bH\x02R\x0ecableConnected\x88\x01\x01\x12\x1f\n" +
	"\vdrive_armed\x18\t \x01(\bR\n" +
	"driveArmed\x126\n" +
	"\n" +
	"accel_mps2\x18\n" +
	" \x01(\v2\x17.komitake.admin.v1.Vec3R\taccelMps2\x122\n" +
	"\bgyro_dps\x18\v \x01(\v2\x17.komitake.admin.v1.Vec3R\agyroDps\x129\n" +
	"\vorientation\x18\f \x01(\v2\x17.komitake.admin.v1.QuatR\vorientation\x12%\n" +
	"\fimu_timer_us\x18\r \x01(\rH\x03R\n" +
	"imuTimerUs\x88\x01\x01B\r\n" +
	"\v_signal_dbmB\n" +
	"\n" +
	"\b_batteryB\x12\n" +
	"\x10_cable_connectedB\x0f\n" +
	"\r_imu_timer_us\"0\n" +
	"\x04Vec3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\">\n" +
	"\x04Quat\x12\f\n" +
	"\x01i\x18\x01 \x01(\x01R\x01i\x12\f\n" +
	"\x01j\x18\x02 \x01(\x01R\x01j\x12\f\n" +
	"\x01k\x18\x03 \x01(\x01R\x01k\x12\f\n" +
	"\x01r\x18\x04 \x01(\x01R\x01r\"\x11\n" +
	"\x0fGetStateRequest\"\xbb\x01\n" +
	"\x10GetStateResponse\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.komitake.admin.v1.StateR\x05state\x12:\n" +
	"\apairing\x18\x02 \x01(\v2 .komitake.admin.v1.PairingRecordR\apairing\x12;\n" +
	"\bwireless\x18\x03 \x01(\v2\x1f.komitake.admin.v1.WirelessInfoR\bwireless\"A\n" +
	"\x0fSetStateRequest\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.komitake.admin.v1.StateR\x05state\"\xbb\x01\n" +
	"\x10SetStateResponse\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.komitake.admin.v1.StateR\x05state\x12:\n" +
	"\apairing\x18\x02 \x01(\v2 .komitake.admin.v1.PairingRecordR\apairing\x12;\n" +
	"\bwireless\x18\x03 \x01(\v2\x1f.komitake.admin.v1.WirelessInfoR\bwireless\"\x17\n" +
	"\x15GetPairingInfoRequest\"T\n" +
	"\x16GetPairingInfoResponse\x12:\n" +
	"\apairing\x18\x01 \x01(\v2 .komitake.admin.v1.PairingRecordR\apairing\"\x14\n" +
	"\x12ListDevicesRequest\"Q\n" +
	"\x13ListDevicesResponse\x12:\n" +
	"\adevices\x18\x01 \x03(\v2 .komitake.admin.v1.DeviceSummaryR\adevices\",\n" +
	"\x14WaitForDeviceRequest\x12\x14\n" +
	"\x05ident\x18\x01 \x01(\tR\x05ident\"Q\n" +
	"\x15WaitForDeviceResponse\x128\n" +
	"\x06device\x18\x01 \x01(\v2 .komitake.admin.v1.DeviceSummaryR\x06device\"G\n" +
	"\x15GetDeviceParamRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"h\n" +
	"\x16GetDeviceParamResponse\x128\n" +
	"\x06device\x18\x01 \x01(\v2 .komitake.admin.v1.DeviceSummaryR\x06device\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"3\n" +
	"\x15GetProductCodeRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\"k\n" +
	"\vProductCode\x12\x12\n" +
	"\x04unk1\x18\x01 \x01(\rR\x04unk1\x12\x1c\n" +
	"\tcharacter\x18\x02 \x01(\rR\tcharacter\x12\x12\n" +
	"\x04unk2\x18\x03 \x01(\rR\x04unk2\x12\x16\n" +
	"\x06serial\x18\x04 \x01(\tR\x06serial\"\x95\x01\n" +
	"\x16GetProductCodeResponse\x128\n" +
	"\x06device\x18\x01 \x01(\v2 .komitake.admin.v1.DeviceSummaryR\x06device\x12A\n" +
	"\fproduct_code\x18\x02 \x01(\v2\x1e.komitake.admin.v1.ProductCodeR\vproductCode\"u\n" +
	"\x0fSetDriveRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x14\n" +
	"\x05steer\x18\x02 \x01(\x01R\x05steer\x12\x1a\n" +
	"\bthrottle\x18\x03 \x01(\x01R\bthrottle\x12\x14\n" +
	"\x05brake\x18\x04 \x01(\x01R\x05brake\"\xc2\x01\n" +
	"\n" +
	"DriveState\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05steer\x18\x02 \x01(\x01R\x05steer\x12\x1a\n" +
	"\bthrottle\x18\x03 \x01(\x01R\bthrottle\x12\x14\n" +
	"\x05brake\x18\x04 \x01(\x01R\x05brake\x12\x18\n" +
	"\aapplied\x18\x05 \x01(\bR\aapplied\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\"G\n" +
	"\x10SetDriveResponse\x123\n" +
	"\x05drive\x18\x01 \x01(\v2\x1d.komitake.admin.v1.DriveStateR\x05drive\"-\n" +
	"\x0fGetDriveRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\"G\n" +
	"\x10GetDriveResponse\x123\n" +
	"\x05drive\x18\x01 \x01(\v2\x1d.komitake.admin.v1.DriveStateR\x05drive\"K\n" +
	"\x13SetDriveModeRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"P\n" +
	"\x14SetDriveModeResponse\x128\n" +
	"\x06device\x18\x01 \x01(\v2 .komitake.admin.v1.DeviceSummaryR\x06device\"1\n" +
	"\x13ShutdownKartRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\"P\n" +
	"\x14ShutdownKartResponse\x128\n" +
	"\x06device\x18\x01 \x01(\v2 .komitake.admin.v1.DeviceSummaryR\x06device\"X\n" +
	"\x12StreamVideoRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12&\n" +
	"\x0ffresh_key_frame\x18\x02 \x01(\bR\rfreshKeyFrame\"\x87\x02\n" +
	"\x13StreamVideoResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"metadata_0\x18\x03 \x01(\x04R\tmetadata0\x12\x1d\n" +
	"\n" +
	"metadata_1\x18\x04 \x01(\x04R\tmetadata1\x12\x1d\n" +
	"\n" +
	"metadata_2\x18\x05 \x01(\x04R\tmetadata2\x12\x1b\n" +
	"\tkey_frame\x18\x06 \x01(\bR\bkeyFrame\x12\x17\n" +
	"\aannex_b\x18\a \x01(\fR\x06annexB\x12$\n" +
	"\rdiscontinuity\x18\b \x01(\bR\rdiscontinuity*T\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"STATE_DOWN\x10\x01\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x02\x12\x11\n" +
	"\rSTATE_PAIRING\x10\x032\xfb\b\n" +
	"\fAdminService\x12S\n" +
	"\bGetState\x12\".komitake.admin.v1.GetStateRequest\x1a#.komitake.admin.v1.GetStateResponse\x12S\n" +
	"\bSetState\x12\".komitake.admin.v1.SetStateRequest\x1a#.komitake.admin.v1.SetStateResponse\x12e\n" +
	"\x0eGetPairingInfo\x12(.komitake.admin.v1.GetPairingInfoRequest\x1a).komitake.admin.v1.GetPairingInfoResponse\x12\\\n" +
	"\vListDevices\x12%.komitake.admin.v1.ListDevicesRequest\x1a&.komitake.admin.v1.ListDevicesResponse\x12b\n" +
	"\rWaitForDevice\x12'.komitake.admin.v1.WaitForDeviceRequest\x1a(.komitake.admin.v1.WaitForDeviceResponse\x12e\n" +
	"\x0eGetDeviceParam\x12(.komitake.admin.v1.GetDeviceParamRequest\x1a).komitake.admin.v1.GetDeviceParamResponse\x12e\n" +
	"\x0eGetProductCode\x12(.komitake.admin.v1.GetProductCodeRequest\x1a).komitake.admin.v1.GetProductCodeResponse\x12S\n" +
	"\bSetDrive\x12\".komitake.admin.v1.SetDriveRequest\x1a#.komitake.admin.v1.SetDriveResponse\x12S\n" +
	"\bGetDrive\x12\".komitake.admin.v1.GetDriveRequest\x1a#.komitake.admin.v1.GetDriveResponse\x12_\n" +
	"\fSetDriveMode\x12&.komitake.admin.v1.SetDriveModeRequest\x1a'.komitake.admin.v1.SetDriveModeResponse\x12_\n" +
	"\fShutdownKart\x12&.komitake.admin.v1.ShutdownKartRequest\x1a'.komitake.admin.v1.ShutdownKartResponse\x12^\n" +
	"\vStreamVideo\x12%.komitake.admin.v1.StreamVideoRequest\x1a&.komitake.admin.v1.StreamVideoResponse0\x01B>Z<github.com/Alex4386/komitake/proto/komitake/admin/v1;adminv1b\x06proto3"

var (
	file_komitake_admin_v1_admin_proto_rawDescOnce sync.Once
	file_komitake_admin_v1_admin_proto_rawDescData []byte
)

func file_komitake_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_komitake_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_komitake_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_komitake_admin_v1_admin_proto_rawDesc), len(file_komitake_admin_v1_admin_proto_rawDesc)))
	})
	return file_komitake_admin_v1_admin_proto_rawDescData
}

var file_komitake_admin_v1_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_komitake_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_komitake_admin_v1_admin_proto_goTypes = []any{
	(State)(0),                     // 0: komitake.admin.v1.State
	(*PairingRecord)(nil),          // 1: komitake.admin.v1.PairingRecord
	(*WirelessInfo)(nil),           // 2: komitake.admin.v1.WirelessInfo
	(*DeviceSummary)(nil),          // 3: komitake.admin.v1.DeviceSummary
	(*Vec3)(nil),                   // 4: komitake.admin.v1.Vec3
	(*Quat)(nil),                   // 5: komitake.admin.v1.Quat
	(*GetStateRequest)(nil),        // 6: komitake.admin.v1.GetStateRequest
	(*GetStateResponse)(nil),       // 7: komitake.admin.v1.GetStateResponse
	(*SetStateRequest)(nil),        // 8: komitake.admin.v1.SetStateRequest
	(*SetStateResponse)(nil),       // 9: komitake.admin.v1.SetStateResponse
	(*GetPairingInfoRequest)(nil),  // 10: komitake.admin.v1.GetPairingInfoRequest
	(*GetPairingInfoResponse)(nil), // 11: komitake.admin.v1.GetPairingInfoResponse
	(*ListDevicesRequest)(nil),     // 12: komitake.admin.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),    // 13: komitake.admin.v1.ListDevicesResponse
	(*WaitForDeviceRequest)(nil),   // 14: komitake.admin.v1.WaitForDeviceRequest
	(*WaitForDeviceResponse)(nil),  // 15: komitake.admin.v1.WaitForDeviceResponse
	(*GetDeviceParamRequest)(nil),  // 16: komitake.admin.v1.GetDeviceParamRequest
	(*GetDeviceParamResponse)(nil), // 17: komitake.admin.v1.GetDeviceParamResponse
	(*GetProductCodeRequest)(nil),  // 18: komitake.admin.v1.GetProductCodeRequest
	(*ProductCode)(nil),            // 19: komitake.admin.v1.ProductCode
	(*GetProductCodeResponse)(nil), // 20: komitake.admin.v1.GetProductCodeResponse
	(*SetDriveRequest)(nil),        // 21: komitake.admin.v1.SetDriveRequest
	(*DriveState)(nil),             // 22: komitake.admin.v1.DriveState
	(*SetDriveResponse)(nil),       // 23: komitake.admin.v1.SetDriveResponse
	(*GetDriveRequest)(nil),        // 24: komitake.admin.v1.GetDriveRequest
	(*GetDriveResponse)(nil),       // 25: komitake.admin.v1.GetDriveResponse
	(*SetDriveModeRequest)(nil),    // 26: komitake.admin.v1.SetDriveModeRequest
	(*SetDriveModeResponse)(nil),   // 27: komitake.admin.v1.SetDriveModeResponse
	(*ShutdownKartRequest)(nil),    // 28: komitake.admin.v1.ShutdownKartRequest
	(*ShutdownKartResponse)(nil),   // 29: komitake.admin.v1.ShutdownKartResponse
	(*StreamVideoRequest)(nil),     // 30: komitake.admin.v1.StreamVideoRequest
	(*StreamVideoResponse)(nil),    // 31: komitake.admin.v1.StreamVideoResponse
}
var file_komitake_admin_v1_admin_proto_depIdxs = []int32{
	0,  // 0: komitake.admin.v1.PairingRecord.state:type_name -> komitake.admin.v1.State
	4,  // 1: komitake.admin.v1.DeviceSummary.accel_mps2:type_name -> komitake.admin.v1.Vec3
	4,  // 2: komitake.admin.v1.DeviceSummary.gyro_dps:type_name -> komitake.admin.v1.Vec3
	5,  // 3: komitake.admin.v1.DeviceSummary.orientation:type_name -> komitake.admin.v1.Quat
	0,  // 4: komitake.admin.v1.GetStateResponse.state:type_name -> komitake.admin.v1.State
	1,  // 5: komitake.admin.v1.GetStateResponse.pairing:type_name -> komitake.admin.v1.PairingRecord
	2,  // 6: komitake.admin.v1.GetStateResponse.wireless:type_name -> komitake.admin.v1.WirelessInfo
	0,  // 7: komitake.admin.v1.SetStateRequest.state:type_name -> komitake.admin.v1.State
	0,  // 8: komitake.admin.v1.SetStateResponse.state:type_name -> komitake.admin.v1.State
	1,  // 9: komitake.admin.v1.SetStateResponse.pairing:type_name -> komitake.admin.v1.PairingRecord
	2,  // 10: komitake.admin.v1.SetStateResponse.wireless:type_name -> komitake.admin.v1.WirelessInfo
	1,  // 11: komitake.admin.v1.GetPairingInfoResponse.pairing:type_name -> komitake.admin.v1.PairingRecord
	3,  // 12: komitake.admin.v1.ListDevicesResponse.devices:type_name -> komitake.admin.v1.DeviceSummary
	3,  // 13: komitake.admin.v1.WaitForDeviceResponse.device:type_name -> komitake.admin.v1.DeviceSummary
	3,  // 14: komitake.admin.v1.GetDeviceParamResponse.device:type_name -> komitake.admin.v1.DeviceSummary
	3,  // 15: komitake.admin.v1.GetProductCodeResponse.device:type_name -> komitake.admin.v1.DeviceSummary
	19, // 16: komitake.admin.v1.GetProductCodeResponse.product_code:type_name -> komitake.admin.v1.ProductCode
	22, // 17: komitake.admin.v1.SetDriveResponse.drive:type_name -> komitake.admin.v1.DriveState
	22, // 18: komitake.admin.v1.GetDriveResponse.drive:type_name -> komitake.admin.v1.DriveState
	3,  // 19: komitake.admin.v1.SetDriveModeResponse.device:type_name -> komitake.admin.v1.DeviceSummary
	3,  // 20: komitake.admin.v1.ShutdownKartResponse.device:type_name -> komitake.admin.v1.DeviceSummary
	6,  // 21: komitake.admin.v1.AdminService.GetState:input_type -> komitake.admin.v1.GetStateRequest
	8,  // 22: komitake.admin.v1.AdminService.SetState:input_type -> komitake.admin.v1.SetStateRequest
	10, // 23: komitake.admin.v1.AdminService.GetPairingInfo:input_type -> komitake.admin.v1.GetPairingInfoRequest
	12, // 24: komitake.admin.v1.AdminService.ListDevices:input_type -> komitake.admin.v1.ListDevicesRequest
	14, // 25: komitake.admin.v1.AdminService.WaitForDevice:input_type -> komitake.admin.v1.WaitForDeviceRequest
	16, // 26: komitake.admin.v1.AdminService.GetDeviceParam:input_type -> komitake.admin.v1.GetDeviceParamRequest
	18, // 27: komitake.admin.v1.AdminService.GetProductCode:input_type -> komitake.admin.v1.GetProductCodeRequest
	21, // 28: komitake.admin.v1.AdminService.SetDrive:input_type -> komitake.admin.v1.SetDriveRequest
	24, // 29: komitake.admin.v1.AdminService.GetDrive:input_type -> komitake.admin.v1.GetDriveRequest
	26, // 30: komitake.admin.v1.AdminService.SetDriveMode:input_type -> komitake.admin.v1.SetDriveModeRequest
	28, // 31: komitake.admin.v1.AdminService.ShutdownKart:input_type -> komitake.admin.v1.ShutdownKartRequest
	30, // 32: komitake.admin.v1.AdminService.StreamVideo:input_type -> komitake.admin.v1.StreamVideoRequest
	7,  // 33: komitake.admin.v1.AdminService.GetState:output_type -> komitake.admin.v1.GetStateResponse
	9,  // 34: komitake.admin.v1.AdminService.SetState:output_type -> komitake.admin.v1.SetStateResponse
	11, // 35: komitake.admin.v1.AdminService.GetPairingInfo:output_type -> komitake.admin.v1.GetPairingInfoResponse
	13, // 36: komitake.admin.v1.AdminService.ListDevices:output_type -> komitake.admin.v1.ListDevicesResponse
	15, // 37: komitake.admin.v1.AdminService.WaitForDevice:output_type -> komitake.admin.v1.WaitForDeviceResponse
	17, // 38: komitake.admin.v1.AdminService.GetDeviceParam:output_type -> komitake.admin.v1.GetDeviceParamResponse
	20, // 39: komitake.admin.v1.AdminService.GetProductCode:output_type -> komitake.admin.v1.GetProductCodeResponse
	23, // 40: komitake.admin.v1.AdminService.SetDrive:output_type -> komitake.admin.v1.SetDriveResponse
	25, // 41: komitake.admin.v1.AdminService.GetDrive:output_type -> komitake.admin.v1.GetDriveResponse
	27, // 42: komitake.admin.v1.AdminService.SetDriveMode:output_type -> komitake.admin.v1.SetDriveModeResponse
	29, // 43: komitake.admin.v1.AdminService.ShutdownKart:output_type -> komitake.admin.v1.ShutdownKartResponse
	31, // 44: komitake.admin.v1.AdminService.StreamVideo:output_type -> komitake.admin.v1.StreamVideoResponse
	33, // [33:45] is the sub-list for method output_type
	21, // [21:33] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_komitake_admin_v1_admin_proto_init() }
func file_komitake_admin_v1_admin_proto_init() {
	if File_komitake_admin_v1_admin_proto != nil {
		return
	}
	file_komitake_admin_v1_admin_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_komitake_admin_v1_admin_proto_rawDesc), len(file_komitake_admin_v1_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_komitake_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_komitake_admin_v1_admin_proto_depIdxs,
		EnumInfos:         file_komitake_admin_v1_admin_proto_enumTypes,
		MessageInfos:      file_komitake_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_komitake_admin_v1_admin_proto = out.File
	file_komitake_admin_v1_admin_proto_goTypes = nil
	file_komitake_admin_v1_admin_proto_depIdxs = nil
}
