// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: komitake/admin/v1/admin.proto

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_GetState_FullMethodName       = "/komitake.admin.v1.AdminService/GetState"
	AdminService_SetState_FullMethodName       = "/komitake.admin.v1.AdminService/SetState"
	AdminService_GetPairingInfo_FullMethodName = "/komitake.admin.v1.AdminService/GetPairingInfo"
	AdminService_ListDevices_FullMethodName    = "/komitake.admin.v1.AdminService/ListDevices"
	AdminService_WaitForDevice_FullMethodName  = "/komitake.admin.v1.AdminService/WaitForDevice"
	AdminService_GetDeviceParam_FullMethodName = "/komitake.admin.v1.AdminService/GetDeviceParam"
	AdminService_GetProductCode_FullMethodName = "/komitake.admin.v1.AdminService/GetProductCode"
	AdminService_SetDrive_FullMethodName       = "/komitake.admin.v1.AdminService/SetDrive"
	AdminService_GetDrive_FullMethodName       = "/komitake.admin.v1.AdminService/GetDrive"
	AdminService_SetDriveMode_FullMethodName   = "/komitake.admin.v1.AdminService/SetDriveMode"
	AdminService_ShutdownKart_FullMethodName   = "/komitake.admin.v1.AdminService/ShutdownKart"
	AdminService_StreamVideo_FullMethodName    = "/komitake.admin.v1.AdminService/StreamVideo"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService is the local control-plane API between clients (CLI, web, SDK)
// and the daemon. It is served over a unix socket (or TCP). It covers daemon
// mode, pairing, connected devices, and Fuji control-plane reads (params /
// product_code).
type AdminServiceClient interface {
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*SetStateResponse, error)
	GetPairingInfo(ctx context.Context, in *GetPairingInfoRequest, opts ...grpc.CallOption) (*GetPairingInfoResponse, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	WaitForDevice(ctx context.Context, in *WaitForDeviceRequest, opts ...grpc.CallOption) (*WaitForDeviceResponse, error)
	// GetDeviceParam reads a Fuji control GetParam value for a connected kart.
	GetDeviceParam(ctx context.Context, in *GetDeviceParamRequest, opts ...grpc.CallOption) (*GetDeviceParamResponse, error)
	// GetProductCode reads product_code via the control port and refreshes the
	// cached device serial.
	GetProductCode(ctx context.Context, in *GetProductCodeRequest, opts ...grpc.CallOption) (*GetProductCodeResponse, error)
	// SetDrive updates teleop axes over the physical Fuji UDP 5102 channel.
	SetDrive(ctx context.Context, in *SetDriveRequest, opts ...grpc.CallOption) (*SetDriveResponse, error)
	// GetDrive returns the last teleop command and verified packet-write status.
	GetDrive(ctx context.Context, in *GetDriveRequest, opts ...grpc.CallOption) (*GetDriveResponse, error)
	// SetDriveMode enables or disables teleoperation for one connected kart.
	SetDriveMode(ctx context.Context, in *SetDriveModeRequest, opts ...grpc.CallOption) (*SetDriveModeResponse, error)
	// ShutdownKart powers off one connected kart via Fuji Control Shutdown (0x09).
	ShutdownKart(ctx context.Context, in *ShutdownKartRequest, opts ...grpc.CallOption) (*ShutdownKartResponse, error)
	// StreamVideo streams complete Annex-B H.264 frames for one connected kart.
	StreamVideo(ctx context.Context, in *StreamVideoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamVideoResponse], error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, AdminService_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*SetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStateResponse)
	err := c.cc.Invoke(ctx, AdminService_SetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetPairingInfo(ctx context.Context, in *GetPairingInfoRequest, opts ...grpc.CallOption) (*GetPairingInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPairingInfoResponse)
	err := c.cc.Invoke(ctx, AdminService_GetPairingInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, AdminService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) WaitForDevice(ctx context.Context, in *WaitForDeviceRequest, opts ...grpc.CallOption) (*WaitForDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitForDeviceResponse)
	err := c.cc.Invoke(ctx, AdminService_WaitForDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetDeviceParam(ctx context.Context, in *GetDeviceParamRequest, opts ...grpc.CallOption) (*GetDeviceParamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceParamResponse)
	err := c.cc.Invoke(ctx, AdminService_GetDeviceParam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetProductCode(ctx context.Context, in *GetProductCodeRequest, opts ...grpc.CallOption) (*GetProductCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductCodeResponse)
	err := c.cc.Invoke(ctx, AdminService_GetProductCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetDrive(ctx context.Context, in *SetDriveRequest, opts ...grpc.CallOption) (*SetDriveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDriveResponse)
	err := c.cc.Invoke(ctx, AdminService_SetDrive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetDrive(ctx context.Context, in *GetDriveRequest, opts ...grpc.CallOption) (*GetDriveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriveResponse)
	err := c.cc.Invoke(ctx, AdminService_GetDrive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetDriveMode(ctx context.Context, in *SetDriveModeRequest, opts ...grpc.CallOption) (*SetDriveModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDriveModeResponse)
	err := c.cc.Invoke(ctx, AdminService_SetDriveMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ShutdownKart(ctx context.Context, in *ShutdownKartRequest, opts ...grpc.CallOption) (*ShutdownKartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownKartResponse)
	err := c.cc.Invoke(ctx, AdminService_ShutdownKart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StreamVideo(ctx context.Context, in *StreamVideoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamVideoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[0], AdminService_StreamVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamVideoRequest, StreamVideoResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_StreamVideoClient = grpc.ServerStreamingClient[StreamVideoResponse]

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService is the local control-plane API between clients (CLI, web, SDK)
// and the daemon. It is served over a unix socket (or TCP). It covers daemon
// mode, pairing, connected devices, and Fuji control-plane reads (params /
// product_code).
type AdminServiceServer interface {
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	SetState(context.Context, *SetStateRequest) (*SetStateResponse, error)
	GetPairingInfo(context.Context, *GetPairingInfoRequest) (*GetPairingInfoResponse, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	WaitForDevice(context.Context, *WaitForDeviceRequest) (*WaitForDeviceResponse, error)
	// GetDeviceParam reads a Fuji control GetParam value for a connected kart.
	GetDeviceParam(context.Context, *GetDeviceParamRequest) (*GetDeviceParamResponse, error)
	// GetProductCode reads product_code via the control port and refreshes the
	// cached device serial.
	GetProductCode(context.Context, *GetProductCodeRequest) (*GetProductCodeResponse, error)
	// SetDrive updates teleop axes over the physical Fuji UDP 5102 channel.
	SetDrive(context.Context, *SetDriveRequest) (*SetDriveResponse, error)
	// GetDrive returns the last teleop command and verified packet-write status.
	GetDrive(context.Context, *GetDriveRequest) (*GetDriveResponse, error)
	// SetDriveMode enables or disables teleoperation for one connected kart.
	SetDriveMode(context.Context, *SetDriveModeRequest) (*SetDriveModeResponse, error)
	// ShutdownKart powers off one connected kart via Fuji Control Shutdown (0x09).
	ShutdownKart(context.Context, *ShutdownKartRequest) (*ShutdownKartResponse, error)
	// StreamVideo streams complete Annex-B H.264 frames for one connected kart.
	StreamVideo(*StreamVideoRequest, grpc.ServerStreamingServer[StreamVideoResponse]) error
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedAdminServiceServer) SetState(context.Context, *SetStateRequest) (*SetStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetState not implemented")
}
func (UnimplementedAdminServiceServer) GetPairingInfo(context.Context, *GetPairingInfoRequest) (*GetPairingInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPairingInfo not implemented")
}
func (UnimplementedAdminServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedAdminServiceServer) WaitForDevice(context.Context, *WaitForDeviceRequest) (*WaitForDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitForDevice not implemented")
}
func (UnimplementedAdminServiceServer) GetDeviceParam(context.Context, *GetDeviceParamRequest) (*GetDeviceParamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceParam not implemented")
}
func (UnimplementedAdminServiceServer) GetProductCode(context.Context, *GetProductCodeRequest) (*GetProductCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductCode not implemented")
}
func (UnimplementedAdminServiceServer) SetDrive(context.Context, *SetDriveRequest) (*SetDriveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDrive not implemented")
}
func (UnimplementedAdminServiceServer) GetDrive(context.Context, *GetDriveRequest) (*GetDriveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDrive not implemented")
}
func (UnimplementedAdminServiceServer) SetDriveMode(context.Context, *SetDriveModeRequest) (*SetDriveModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDriveMode not implemented")
}
func (UnimplementedAdminServiceServer) ShutdownKart(context.Context, *ShutdownKartRequest) (*ShutdownKartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShutdownKart not implemented")
}
func (UnimplementedAdminServiceServer) StreamVideo(*StreamVideoRequest, grpc.ServerStreamingServer[StreamVideoResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamVideo not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetState(ctx, req.(*SetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetPairingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPairingInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetPairingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetPairingInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetPairingInfo(ctx, req.(*GetPairingInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_WaitForDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitForDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).WaitForDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_WaitForDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).WaitForDevice(ctx, req.(*WaitForDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetDeviceParam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceParamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetDeviceParam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetDeviceParam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetDeviceParam(ctx, req.(*GetDeviceParamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetProductCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetProductCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetProductCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetProductCode(ctx, req.(*GetProductCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDriveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SetDrive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetDrive(ctx, req.(*SetDriveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetDrive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetDrive(ctx, req.(*GetDriveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetDriveMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDriveModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetDriveMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SetDriveMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetDriveMode(ctx, req.(*SetDriveModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ShutdownKart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownKartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ShutdownKart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ShutdownKart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ShutdownKart(ctx, req.(*ShutdownKartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StreamVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamVideoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).StreamVideo(m, &grpc.GenericServerStream[StreamVideoRequest, StreamVideoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_StreamVideoServer = grpc.ServerStreamingServer[StreamVideoResponse]

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "komitake.admin.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _AdminService_GetState_Handler,
		},
		{
			MethodName: "SetState",
			Handler:    _AdminService_SetState_Handler,
		},
		{
			MethodName: "GetPairingInfo",
			Handler:    _AdminService_GetPairingInfo_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _AdminService_ListDevices_Handler,
		},
		{
			MethodName: "WaitForDevice",
			Handler:    _AdminService_WaitForDevice_Handler,
		},
		{
			MethodName: "GetDeviceParam",
			Handler:    _AdminService_GetDeviceParam_Handler,
		},
		{
			MethodName: "GetProductCode",
			Handler:    _AdminService_GetProductCode_Handler,
		},
		{
			MethodName: "SetDrive",
			Handler:    _AdminService_SetDrive_Handler,
		},
		{
			MethodName: "GetDrive",
			Handler:    _AdminService_GetDrive_Handler,
		},
		{
			MethodName: "SetDriveMode",
			Handler:    _AdminService_SetDriveMode_Handler,
		},
		{
			MethodName: "ShutdownKart",
			Handler:    _AdminService_ShutdownKart_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamVideo",
			Handler:       _AdminService_StreamVideo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "komitake/admin/v1/admin.proto",
}
