// Package lp2p builds the encrypted vendor information elements and static
// CCMP key that a Fuji kart's LP2P access point advertises.
package lp2p

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	_ "embed"
	"encoding/binary"
	"errors"
	"math"
	mathrand "math/rand"
	"time"
)

const (
	pskSize                     = 32
	localCommunicationID uint64 = 0x0100ED100BA3A000
	seqPeriod                   = 30 * 60
	nonceTableSize              = 0x10000 * 16
)

//go:generate go run gennonces.go

var (
	// lp2p_nonces.bin is generated by gennonces.go; run `go generate ./internal/wireless/lp2p`.
	//go:embed lp2p_nonces.bin
	nonces []byte

	wellKnownNoncePrefix = []byte("WellKnownStr")
	revision             = uint16(0x0001)
	defaultBeaconTLVs    = []tlv{
		{typ: 0x01, value: []byte{0x20, 0x13}},
		{typ: 0x02, value: []byte{0, 0, 0, 0, 0, 0, 0, 0x04}},
	}
	defaultAppTLVs = []tlv{
		{typ: 0x21, value: []byte{}},
	}
)

var seq = struct {
	value int
	set   bool
}{}

// Network is the encrypted material hostapd needs to beacon an LP2P BSS.
type Network struct {
	StaticCCMPKey []byte
	VendorIEs     []byte
}

type tlv struct {
	typ   byte
	value []byte
}

// Encrypt derives the static CCMP key and vendor IEs for the given PSK. When
// temporary is true a pure-random nonce is used; otherwise nonces are drawn
// sequentially to reduce reuse for a long-lived game network.
func Encrypt(psk []byte, temporary bool) (Network, error) {
	if len(psk) != pskSize {
		return Network{}, errors.New("lp2p requires a 32-byte psk")
	}
	if len(nonces) != nonceTableSize {
		return Network{}, errors.New("lp2p nonce table has unexpected size")
	}

	plainNonce, encryptedNonce, err := getNoncePair(temporary)
	if err != nil {
		return Network{}, err
	}

	ad0 := make([]byte, 0x20)
	ad0[0] = 0x20
	ad0[1] = 0x02
	ad0[2] = 0x02
	binary.BigEndian.PutUint64(ad0[0x04:0x0C], localCommunicationID)
	copy(ad0[0x0C:0x1C], encryptedNonce)
	if _, err := rand.Read(ad0[0x1C:0x20]); err != nil {
		return Network{}, err
	}
	iv0 := append(append([]byte(nil), ad0[0x1C:0x20]...), make([]byte, 8)...)

	ad1 := make([]byte, 4)
	if _, err := rand.Read(ad1); err != nil {
		return Network{}, err
	}
	iv1 := append(append([]byte(nil), ad1...), make([]byte, 8)...)

	keyA, keyC := deriveKeys(plainNonce, psk)
	keyB, _ := deriveKeys(plainNonce, localCommunicationIDBytesLE())

	enc0, tag0, err := gcmEncrypt(keyB, iv0, packTLVs(defaultBeaconTLVs), ad0)
	if err != nil {
		return Network{}, err
	}
	enc1, tag1, err := gcmEncrypt(keyC, iv1, packTLVs(defaultAppTLVs), ad1)
	if err != nil {
		return Network{}, err
	}

	ie0 := append([]byte{}, ad0...)
	ie0 = append(ie0, tag0...)
	ie0 = append(ie0, enc0...)

	ie1 := append([]byte{}, ad1...)
	ie1 = append(ie1, tag1...)
	ie1 = append(ie1, enc1...)

	vendor := appendVendorIE(0, ie0)
	vendor = append(vendor, appendVendorIE(1, ie1)...)
	return Network{
		StaticCCMPKey: keyA,
		VendorIEs:     vendor,
	}, nil
}

func deriveKeys(nonce []byte, keyMaterial []byte) ([]byte, []byte) {
	inner := hmacSHA256(nonce, keyMaterial)
	combined := hmacSHA256(inner, []byte{0x02, 0x01})
	return append([]byte(nil), combined[:16]...), append([]byte(nil), combined[16:]...)
}

func hmacSHA256(key []byte, msg []byte) []byte {
	h := hmac.New(sha256.New, key)
	_, _ = h.Write(msg)
	return h.Sum(nil)
}

func gcmEncrypt(key []byte, iv []byte, plaintext []byte, aad []byte) ([]byte, []byte, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, nil, err
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, nil, err
	}
	encrypted := gcm.Seal(nil, iv, plaintext, aad)
	tagSize := gcm.Overhead()
	return encrypted[:len(encrypted)-tagSize], encrypted[len(encrypted)-tagSize:], nil
}

func getNoncePair(temporary bool) ([]byte, []byte, error) {
	var index uint16
	if temporary {
		index = uint16(mathrand.New(mathrand.NewSource(time.Now().UnixNano())).Intn(math.MaxUint16 + 1))
	} else {
		index = nextSequenceIndex()
	}

	plain := make([]byte, 16)
	copy(plain[:12], wellKnownNoncePrefix)
	binary.BigEndian.PutUint16(plain[12:14], revision)
	binary.BigEndian.PutUint16(plain[14:16], index)

	offset := int(index) * 16
	encrypted := append([]byte(nil), nonces[offset:offset+16]...)
	return plain, encrypted, nil
}

func nextSequenceIndex() uint16 {
	if !seq.set {
		seq.value = mathrand.New(mathrand.NewSource(time.Now().UnixNano())).Intn(16)
		seq.set = true
	}
	seq.value = (seq.value + 1) & 0xF
	now := int(time.Now().Unix())
	return uint16(((now / seqPeriod) << 4) | seq.value)
}

func localCommunicationIDBytesLE() []byte {
	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, localCommunicationID)
	return buf
}

func packTLVs(tags []tlv) []byte {
	var out []byte
	for _, tag := range tags {
		out = append(out, tag.typ, byte(len(tag.value)))
		out = append(out, tag.value...)
	}
	return out
}

func appendVendorIE(id byte, payload []byte) []byte {
	ie := append([]byte{0x00, 0x22, 0xaa, 0x06, id}, payload...)
	out := []byte{0xdd, byte(len(ie))}
	out = append(out, ie...)
	return out
}
